version: "3"

services:
  namenode:
    image: hadoop:v1
    command: bin/hdfs --config /usr/hadoop/etc/hadoop --hostnames namenode namenode
    hostname: namenode
    ports:
      - "50070:50070"
    networks:
      - hadoopv1


  datanode:
    image: hadoop:v1
    command: bin/hdfs --config /usr/hadoop/etc/hadoop --hostnames datanode datanode
    hostname: datanode
    deploy:
      replicas: 1
      update_config:
        parallelism: 2
        delay: 10s
      restart_policy:
        condition: on-failure
    networks:
      - hadoopv1
    volumes:
      - /root/hadoop/dfs/data:/root/hadoop/dfs/data

networks:
  hadoopv1:
    driver: overlay














