version: "3.3"

services:
  namenode:
    image: hadoop:v1
    command: bin/hdfs --config /usr/hadoop/etc/hadoop --hostnames namenode namenode
    hostname: namenode
    ports:
      - "50070:50070"
    networks:
      - hadoopv1
    volumes:
      - /root/hadoop/dfs/name:/root/hadoop/dfs/name
    deploy:
      placement:
        constraints:
          - node.hostname == master


  datanode:
    image: hadoop:v1
    command: bin/hdfs --config /usr/hadoop/etc/hadoop datanode
    networks:
      - hadoopv1
    configs:
      - source: slaves
        target: /usr/hadoop/etc/hadoop/slaves
    deploy:
      replicas: 3
      update_config:
        parallelism: 2
        delay: 10s
      restart_policy:
        condition: on-failure



configs:
  slaves:
    external: true


networks:
  hadoopv1:
    driver: overlay














